name: Build PAM Wrongpass Module

on:
  workflow_dispatch:
  push:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential libpam0g-dev

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.24.2'

      - name: Build shared library
        run: go build -buildmode=c-shared -o pam_wrongpass.so pam_wrongpass.go
