name: Build PAM Wrongpass Module

permissions:
  contents: read

on:
  workflow_dispatch:
  push:
    tags: ['v*.*.*']
    branches: [main]
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  build-amd64:
    runs-on: ubuntu-latest
    permissions: write-all
    strategy:
      matrix:
        go: ['1.24.2']
        arch: [amd64]
        os: [linux]
    steps:
      - uses: actions/checkout@v5

      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libpam0g-dev

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: ${{ matrix.go }}

      - name: Build for ${{ matrix.os }}_${{ matrix.arch }}.so
        run: |
          CGO_ENABLED=1 GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} \
          go build -buildmode=c-shared -o pam_wrongpass_${{ matrix.os }}_${{ matrix.arch }}.so pam_wrongpass.go
          file pam_wrongpass_${{ matrix.os }}_${{ matrix.arch }}.so

      - name: Upload pam_wrongpass_${{ matrix.os }}_${{ matrix.arch }}.so artifact
        uses: actions/upload-artifact@v4
        with:
          name: pam_wrongpass_${{ matrix.os }}_${{ matrix.arch }}.so
          path: pam_wrongpass_${{ matrix.os }}_${{ matrix.arch }}.so

  build-arm64:
    runs-on: ubuntu-latest
    permissions: write-all
    strategy:
      matrix:
        go: ['1.24.2']
        arch: [arm64]
        os: [linux]
    steps:
      - uses: actions/checkout@v5

      # Kør arm64 userspace via QEMU
      - name: Build on aarch64 (QEMU)
        uses: uraimo/run-on-arch-action@v3
        with:
          arch: aarch64
          distro: ubuntu22.04
          githubToken: ${{ github.token }}
          install: |
            apt-get update
            DEBIAN_FRONTEND=noninteractive apt-get install -y \
              build-essential libpam0g-dev curl ca-certificates file
            curl -fsSL https://go.dev/dl/go1.24.2.linux-${{ matrix.arch }}.tar.gz -o /tmp/go.tar.gz
            tar -C /usr/local -xzf /tmp/go.tar.gz
            echo 'export PATH=/usr/local/go/bin:$PATH' >> /etc/profile
          run: |
            . /etc/profile
            go version
            go env
            CGO_ENABLED=1 GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} \
              go build -buildmode=c-shared -o pam_wrongpass_${{ matrix.os }}_${{ matrix.arch }}.so pam_wrongpass.go
            file pam_wrongpass_${{ matrix.os }}_arm64.so

      - name: Upload ${{ matrix.arch }} artifact
        uses: actions/upload-artifact@v4
        with:
          name: pam_wrongpass_${{ matrix.os }}_${{ matrix.arch }}.so
          path: pam_wrongpass_${{ matrix.os }}_${{ matrix.arch }}.so
