name: Build PAM Wrongpass Module

permissions: read-all

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    strategy:
      matrix:
        go: ['1.24.2']
        arch: [amd64]
    steps:
      - uses: actions/checkout@v5

      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libpam0g-dev

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: ${{ matrix.go }}

      - name: Build .so
        env:
          CGO_ENABLED: '1'
          GOOS: linux
          GOARCH: ${{ matrix.arch }}
        run: |
          go build -buildmode=c-shared -o ./pam_wrongpass_linux_${{ matrix.arch }}.so pam_wrongpass.go
          file pam_wrongpass_linux_${{ matrix.arch }}.so

      - name: Upload ${{ matrix.arch }} artifact
        uses: actions/upload-artifact@v4
        with:
          name: pam_wrongpass_linux_${{ matrix.arch }}.so
          path: pam_wrongpass_linux_${{ matrix.arch }}.so
