name: Build PAM Wrongpass Module

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential libpam0g-dev

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.23'

      - name: Build shared library
        run: go build -buildmode=c-shared -o pam_wrongpass.so pam_wrongpass.go

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: pam_wrongpass.so
          path: pam_wrongpass.so

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: pam_wrongpass.so
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
